---
- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: update_system

- name: reboot VMs
  reboot:
    connect_timeout: 20
    reboot_timeout: 300
  register: reboot_result
  when: update_system.changed

- name: VMs restarted and online again
  debug:
    msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."
  when: update_system.changed
