
---
- name: Ensure required repos are installed
  include_tasks: repos.yml
  tags: repos

- name: Update all packages and reboot
  include_tasks: update.yml
  tags: update

- name: Ensure required packages are installed
  include_tasks: packages.yml
  tags: packages

- name: Ensure Network is properly configured
  include_tasks: network.yml
  tags: network
