---
- name: Register Machine with redhat_subscription user on Redhat and auto-subscribe to available content.
  redhat_subscription:
    state: present
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    auto_attach: true
  ignore_errors: yes

- name: Register Machine with activationkey on Redhat and auto-subscribe to available content.
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ organization_id }}"
    auto_attach: true
  ignore_errors: yes

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
  ignore_errors: yes

- name: Ensure required repos are enabled
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: enabled
  ignore_errors: yes
