---
- name: Register Machine on Redhat and auto-subscribe to available content.
  redhat_subscription:
    state: present
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    auto_attach: true
  when: "{{ rhel_subscription_user }}" is defined

# - name: Register Machine on Redhat and auto-subscribe to available content.
#   redhat_subscription:
#     state: present
#     username: "{{ rhel_subscription_user }}"
#     password: "{{ rhel_subscription_pass }}"
#     auto_attach: true
#   when: ("{{ rhel_subscription_user }}" is defined) and ("{{ rhel_subscription_pass }}" is defined) and ("{{ rhel_subscription_pass }}" | length > 0) and ("{{ rhel_subscription_user }}" | length > 0)

# - name: Register Machine on Redhat and auto-subscribe to available content.
#   redhat_subscription:
#     state: present
#     activationkey: "{{ activation_key }}"
#     org_id: "{{ organization_id }}"
#     auto_attach: true
#   #  pool_ids: 'xx'
#   when: ("{{ activation_key }}" is defined) and "({{ organization_id }}" is defined) and ("{{ activation_key }}" | length > 0) and ("{{ organization_id }}" | length > 0)

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
  ignore_errors: yes

- name: Ensure required repos are enabled
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: enabled
