---
- name: Populate service facts
  service_facts:

- name: Open port 443
  firewalld:
    service: https
    permanent: yes
    state: enabled
  when: ansible_facts.services['firewalld.service'] is defined

- name: Open port 80
  firewalld:
    service: http
    permanent: yes
    state: enabled
  when: ansible_facts.services['firewalld.service'] is defined

- name: Open port 9000 to see HA-Proxy stats
  firewalld:
    port: 9000/tcp
    permanent: yes
    state: enabled
  when: ansible_facts.services['firewalld.service'] is defined
  notify: reload firewalld

- debug:
    msg: firewalld installed!
  when: ansible_facts.services['firewalld.service'] is defined

- debug:
    msg: iptables installed!
  when: ansible_facts.services['iptables.service'] is defined

- name: Reject tcp with icmp-host-prohibited
  iptables:
    chain: INPUT
    reject_with: icmp-host-prohibited
    state: absent
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow related and established connections
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow traffic to loopback
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: yes
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow traffic from loopback
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
  become: yes
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new incoming SYN packets on TCP port 22 (SSH).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    ctstate: NEW,ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new outgoing SYN packets on TCP port 22 (SSH).
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: '22'
    ctstate: ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept OUTPUT SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new incoming SYN packets on TCP port 80 (HTTP).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    ctstate: NEW,ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new outgoing SYN packets on TCP port 80 (HTTP).
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: '80'
    ctstate: ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept OUTPUT SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new incoming SYN packets on TCP port 443 (HTTPS).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    ctstate: NEW,ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new outgoing SYN packets on TCP port 443 (HTTPS).
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: '443'
    ctstate: ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept OUTPUT SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new incoming SYN packets on TCP port 9000 (HA-PROXY stats).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '9000'
    ctstate: NEW,ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Allow new outgoing SYN packets on TCP port 9000 (HA-PROXY stats).
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: '9000'
    ctstate: ESTABLISHED
    syn: match
    jump: ACCEPT
    comment: Accept OUTPUT SSH connections.
  when: ansible_facts.services['iptables.service'] is defined

- name: Reject tcp with icmp-host-prohibited
  iptables:
    chain: INPUT
    reject_with: icmp-host-prohibited
    state: present
  when: ansible_facts.services['iptables.service'] is defined
