---
- name: Increase nofile soft limits for user haproxy to 64000
  pam_limits:
    domain: haproxy
    limit_type: soft
    limit_item: nofile
    value: '64535'

- name: Increase nofile hard limits for user haproxy to 64000
  pam_limits:
    domain: haproxy
    limit_type: hard
    limit_item: nofile
    value: '64535'

- name: Increase nproc soft limits for user haproxy to 64000
  pam_limits:
    domain: haproxy
    limit_type: soft
    limit_item: nproc
    value: '64535'

- name: Increase nproc hard limits for user haproxy to 64000
  pam_limits:
    domain: haproxy
    limit_type: hard
    limit_item: nproc
    value: '64535'
